test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  collation: utf8_unicode_ci
  database: testschema_migrations
  pool: 5
  username: root
  password: "12345678"

development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  database: upload_demo
  host: 127.0.0.1
  pool: 5
  username: root
  password: "12345678"

production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  database: sunshine
  pool: 5
  username:
  password: "123456"
