development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: test
  pool: 5
  username: root
  password: 123456
  host: localhost
  
production:
  adapter: em_mysql2
  encoding: utf8
  reconnect: true
  database: test
  pool: 200
  username: root
  password: 123456
  host: localhost
