source 'http://mirrors.tuna.tsinghua.edu.cn/rubygems'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.2'
gem 'mysql2', '~> 0.4.10'
gem 'devise'

gem 'pundit'

gem 'unicorn'
gem 'puma'
gem 'yettings'
gem 'mina'
gem 'mina-sidekiq', :require => false
gem 'mina-unicorn', :require => false

gem 'sass-rails', '~> 5.0'
gem 'sass'
gem 'font-awesome-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'gon'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

gem 'therubyracer'
gem 'rest-client'

#search_form_for
gem 'ransack'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'aliyun-oss-sdk', '~> 0.1.8'
gem "carrierwave", "0.8.0"
gem 'carrierwave-aliyun', '~> 0.7.0'
gem 'mini_magick'

gem 'will_paginate', '~> 3.1.0'
gem 'will_paginate-bootstrap'

gem "redis",'>=3.2.1'
gem "hiredis"
gem 'sidekiq','>=3.5.1'
gem 'sinatra', require: false
gem 'china_sms'
gem 'wx_pay'
gem 'whenever', require: false


group :development, :test do
  gem 'byebug', '10.0.1', platform: :mri
  gem 'pry'
  gem "pry-nav"
  gem 'pry-rails', '0.3.2' # binding.pry
end

group :development do
  #gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.8'
  #gem 'spring'
  #gem 'spring-watcher-listen', '~> 2.0.0'
end

gem "signature"
gem 'symmetric-encryption'

gem 'rails_kindeditor'
gem 'simple_xlsx_reader'
gem 'spreadsheet'

group :production do
  gem 'unicorn-worker-killer'
end

# 下拉框搜索
gem "select2-rails"

